name: Reusable Deploy

on: 
  workflow_call:
    inputs:
        artifact-name:
            required: false
            type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
        job-result: ${{ steps.output-result.outputs.deployment-result }}
    steps:
      - name: Pseudo Deployment
        run: echo "Deploying App"
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name : Output artifacts
        run: ls
      - name: Output Result
        id: output
        run: echo "deployment-result=This is an output" >> $GITHUB_OUTPUT
