name: FirstWorkflow

on: [push, workflow_dispatch]
  

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
        
      - name: Print a second step
        run: | 
          echo "Another Step"
          echo "Another Step 2"
          

      - name: Print a third step
        shell: python
        run: print("Woaw A Python Step")

