name: FirstWorkflow

on: [push, workflow_dispatch]

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Info
        run: |
          hostname
          pwd
          ls

      - name: Create a file
        run: |
          ls -al
          echo "One line" | tee myfile.log

      - name: a final step
        run: ls -al

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: check file there
        env:
          MY_ENV_VAR: "DefaultValue"
        run: |
          hostname
          pwd
          ls -al
          echo "Value: $MY_ENV_VAR"
